### PR TITLE
Add ebib-download-url to download papers linked in the url field

### PR DESCRIPTION
**Pull request by akoehn**
This is useful if a bibtex entry already contains a link to a paper. `ebib-download-url` will download that paper and name it after the bibtex key of the entry.

It might not be perfect (does not handle non-pdf urls except arxiv) but I had it in my .emacs for some time and thought it would be a good idea to upstream it.

### CODE REVIEW

**Comment by joostkremers** [comment]
I'd love to have something like this integrated with Ebib, but I'm wondering if we could perhaps leverage the [biblio](https://github.com/cpitclaudel/biblio.el) package to do this. I've been meaning to look into `biblio` and see if it can be integrated in Ebib, but I've never gotten round to it. (Mostly because none of the archives built into `biblio` support the field I'm in...)

`biblio` has the ability to download pdfs, although not (as far as I can tell; I haven't looked at the code) by taking a URL in an entry and using that to find the location of the pdf, so that would be nice to have. I'd prefer it to be part of some more comprehensive integration of `biblio` with Ebib, though. I don't know if that would be something you'd be interested in working on, but I'd certainly accept a PR to that effect.

**Comment by akoehn** [comment]
I had a look at biblio and it only allows to download pdfs from specific sources such as arxiv.  There is currently no additional infrastructure for downloading papers that are linked in the `url` field of an already existing bibtex entry.

As biblio is a tool to get bibliographic information from a specific set of sources, the general url downloading is probably out of scope for that package.

**Comment by chrikoehn** [comment]
@joostkremers what kind of biblio integration do you have in mind? I think there are two different use cases, one where you don't know the URL and one where you do. Of course, it would be nice to have both covered like "download the pdf from the URL, and if that's not possible, search for it" but in the mean time I'll use @akoehn's code because the main use case for me is that I have an entry with a URL and don't need to search for it.

**Comment by joostkremers** [comment]
I see now that biblio doesn't do what I thought it did. :smile: @akhoen's code does something different, so obviously it should be merged. I'd like to make it a bit more customisable, so a user can add more Internet sources.

I'll be pushing it to the devel branch first, so feel free to check it out there if you like.

**Comment by joostkremers** [comment]
Any suggestions for a key binding? :smile:

**Comment by akoehn** [comment]
I don't know; I don't have it on a key binding. I mostly just used `M-x ebi do`and after that `M-x <Ret>` because I tend to add stuff in bulk:-)

**Comment by akoehn** [comment]
@joostkremers, if you think that this kind of interface fits well, I might implement it in the next few days.

**Comment by joostkremers** [comment]
Yeah, that would be a good idea. I'd suggest to keep `ebib-download-url` as an interactive function, so it's still possible to `M-x` it directly.

**Comment by chrikoehn** [comment]
I've just noticed that the function's behaviour could be polished a bit: Sometimes the URL field does not lead to the document directly but to an overview page. In this case, the webpage would be stored. If I notice that, I change the URL to point to the document directly and do `M-x ebib-download-url` which replaces the file and appends the path to the `file` field. The behaviour I would expect is: Ask user whether to replace file and if so, do not append the path to the 'file' field.

**Comment by joostkremers** [comment]
@chrikoehn I guess what you mean is that `ebib-download-url` should do a bit more error checking. :smile:

What's happening is that the URL doesn't match anything in `ebib-url-download-transformations`, so that it's not possible to convert the URL into the URL for the corresponding pdf file. The best way to handle this is to check whether the URL actually ends in `.pdf` and if it's not, ask the user for confirmation that this URL is correct, giving them the opportunity to modify it.

**Comment by joostkremers** [comment]
I just added a commit that checks if the download URL really looks like a pdf file and gives you the option to change the URL if it isn't, or cancel the download.

The second problem you mention, that the file is added to the `file` list even if it overwrites an existing file is another issue. I'll see what I can do about that.

**Comment by joostkremers** [comment]
With the latest commit, `ebib-download-url` now checks whether a file is already listed in the `file` field before adding it.

I think the function is now good enough to be included in the master branch. Thank you both for your input and suggestions.

The only thing lacking are mappings between URLs and their corresponding pdf files, i.e., entries for `ebib-url-download-transformations`.

Of course, any suggestions on improving the functionality of `ebib-download-url` are always welcome!

**Comment by akoehn** [comment]
Thank you for these enhancements!  I noted the question regarding the URL yesterday and it makes the functionality much less ad-hoc than the way I originally wrote it :-)

**Pull request closed without merging**
