### PR TITLE
Debian and Ubuntu installation instructions

### PR DESCRIPTION
**Pull request by spwhitton**
This ELPA package is now available from the Debian and Ubuntu package
repositories.

### CODE REVIEW

**Comment by joostkremers** [comment]
Perhaps I should point out that ebib isn't strictly speaking an ELPA package: it is not available on <http://elpa.gnu.org>. Wouldn't it be confusing to package it as `elpa-ebib`?

**Comment by joostkremers** [comment]
After all, `dash-el`, which is a dependency of Ebib, isn't called `elpa-dash`...

**Comment by spwhitton** [comment]
Actually, the packaging of dash-el in Debian will migrate to elpa-dash
at some point.  We use 'elpa' as a general term for *an* Emacs Lisp
Packaging Archive package, rather than any particular archive.  I
suppose the choice could be argued about, but it's the convention we've
adopted for all Emacs Lisp packages from now on.

**Comment by joostkremers** [comment]
I'm fine with the name, just wanted to make sure there wasn't any mistake.

**Pull request merged**
